app:
  max_price_eur: 400
  max_average_minutes: 60
  max_single_trip_minutes: 75
  min_samples_per_destination: 3
  timezone: Europe/Belgrade

routing:
  # Tipični termini radnim danom. Za svaki novi oglas računaju se obe destinacije.
  sample_times:
    - "07:30"
    - "09:00"
    - "14:00"
    - "17:00"

destinations:
  - name: "Fakultet 1"
    lat: 44.855010356940085
    lon: 20.38110204129845
  - name: "Fakultet 2"
    lat: 44.81881998489189
    lon: 20.456654438685682

sources:
  four_zida:
    enabled: true
    search_url: "https://www.4zida.rs/izdavanje-stanova/beograd/do-400-evra?sortiranje=najnoviji"
    max_new_details_per_run: 20
    request_delay_seconds: 1.2

notifications:
  telegram:
    enabled: true
